sudo: required
services:
  - docker

before_install:
  - docker build -t docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true docker-react-app yarn test --coverage

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'docker-react'
  env: 'DockerReact-env'
  bucket_name: 'elasticbeanstalk-us-east-2-699328816545'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
